### ISSUE TITLE
On click event handling on echartsInstance is not working

### ISSUE THREAD

**Issue by treto** [VolkovLabs/volkovlabs-echarts-panel#79]
Hi,

I've been playing with the echarts instance with the goal to select some custom filters and variables. I've tried adding an onClick listener to the echarts Instance. Please correct me if I'm wrong, but after adding it with a simple console.log() I should at least be able to see something whenever I click on the plugin widget?

Minimal code example (default apache echarts javascript code and https://github.com/VolkovLabs/volkovlabs-echarts-panel#events-handling

Expected behavior would be that any console log is printed in the browser console.

Versions:
 `volkovlabs-echarts-panel-3.5.0` 
`grafana v9.2.4`

```javascript
echartsInstance.on('click', (params) => {
  console.log("something's happened!");
});


// console.log(echartsInstance)
const series = data.series.map((s) => {
  const sData = s.fields.find((f) => f.type === 'number').values.buffer;
  const sTime = s.fields.find((f) => f.type === 'time').values.buffer;

  return {
    name: s.name,
    type: 'line',
    showSymbol: false,
    areaStyle: {
      opacity: 0.1,
    },
    lineStyle: {
      width: 1,
    },
    data: sData.map((d, i) => [sTime[i], d.toFixed(2)]),
  };
});

const axisOption = {
  axisTick: {
    show: false,
  },
  axisLine: {
    show: false,
  },
  axisLabel: {
    color: 'rgba(128, 128, 128, .9)',
  },
  splitLine: {
    lineStyle: {
      color: 'rgba(128, 128, 128, .2)',
    },
  },
};

let options = {
  backgroundColor: 'transparent',
  tooltip: {
    trigger: 'axis',
  },
  legend: {
    left: '0',
    bottom: '0',
    data: data.series.map((s) => s.name),
    textStyle: {
      color: 'rgba(128, 128, 128, .9)',
    },
  },
  xAxis: Object.assign(
    {
      type: 'time',
    },
    axisOption
  ),
  yAxis: Object.assign(
    {
      type: 'value',
      min: 'dataMin',
    },
    axisOption
  ),
  grid: {
    left: 0,
    right: 16,
    top: 6,
    bottom: 24,
    containLabel: true,
  },
  series,
};

return options
```

**Comment by mikhail-vl** [comment]
@treto It's a good question.

  Are you click on the graph points/objects or blank areas? If a blank area, then event handling should be done differently.

  Please take a look at the official documentation: https://apache.github.io/echarts-handbook/en/concepts/event/.
  Let me know if it helps.

  I will add a reference to the official documentation in the README later today.

**Comment by treto** [comment]
Hi @mikhail-vl 

Thanks for a prompt reply. I've had a look at the official docs in regards to events on chart level and it seems pretty similar to what I've been doing.

Then, I've updated from 3.5.0 to 3.7.0 (in your change longs there's a note that event handling was fixed between these versions). I've tried clicking on everything and *sometimes* I would get a response (onclick for echartInstance), I couldn't pinpoint and get a clear way to reproduce the output though.

Having a deeper look at the docs, there's a `graphic` field in options which seems to be doing what I've been looking for (so custom buttons). Minimal example is below. Oddly enough, it seems that if echartsInstance as an onclick registered, it will be invoked whenever a child (I guess all graphic objects) is clicked. Notice that if you click on the text in the example below it will only output "test2" and you press on the rectangle (with another onclick registered) it will call onclick event handler for rectangle first and then call the one for echartsInstance.

Reference: https://echarts.apache.org/en/option.html#graphic

```javascript
echartsInstance.on('click', function (params) {
  console.log("test2");
});

const series = data.series.map((s) => {
  const sData = s.fields.find((f) => f.type === 'number').values.buffer;
  const sTime = s.fields.find((f) => f.type === 'time').values.buffer;

  return {
    name: s.name,
    type: 'line',
    showSymbol: false,
    areaStyle: {
      opacity: 0.1,
    },
    lineStyle: {
      width: 1,
    },
    data: sData.map((d, i) => [sTime[i], d.toFixed(2)]),
  };
});

const axisOption = {
  axisTick: {
    show: false,
  },
  axisLine: {
    show: false,
  },
  axisLabel: {
    color: 'rgba(128, 128, 128, .9)',
  },
  splitLine: {
    lineStyle: {
      color: 'rgba(128, 128, 128, .2)',
    },
  },
};

return {
  backgroundColor: 'transparent',
  tooltip: {
    trigger: 'axis',
  },
  legend: {
    left: '0',
    bottom: '0',
    data: data.series.map((s) => s.name),
    textStyle: {
      color: 'rgba(128, 128, 128, .9)',
    },
  },
  xAxis: Object.assign(
    {
      type: 'time',
    },
    axisOption
  ),
  yAxis: Object.assign(
    {
      type: 'value',
      min: 'dataMin',
    },
    axisOption
  ),
  grid: {
    left: 0,
    right: 16,
    top: 6,
    bottom: 24,
    containLabel: true,
  },
  series,
  graphic: [
    {
      type: 'group',
      bounding: 'raw',
      right: 55,
      bottom: 55,
      z: 100,
      children: [
        {
          type: 'rect',
          left: 'center',
          top: 'center',
          z: 100,
          shape: {
            width: 400,
            height: 50
          },
          style: {
            fill: 'rgba(0,0,0,0.3)'
          },
          onclick: function () {
            console.log("test")
          },
        },
        {
          type: 'text',
          left: 'center',
          top: 'center',
          z: 100,
          style: {
            fill: '#fff',
            text: 'ECHARTS LINE CHART',
            font: 'bold 26px sans-serif'
          }
        }
      ]
    }
  ]
};
```

**Comment by mikhail-vl** [comment]
@treto The latest version 3.7.0 did not fix anything regarding event handlers, it was about updating documentation for event handler in the README.

  I tried your script and can confirm that it works as expected from my point of view:
1. Click on any Objects displays one notifications.
2. Click on `rect` object displays multiple notifications.
3. Click on `text` object displays one notifications.

  I have used `notifySuccess['Click', 'Hello']`, which is a new feature in v3.7.0 instead of `console.log`. I would highly recommend to try using it. It is a Grafana style notifications instead of Console output.

  Do you have any concerns with current event handler behavior in Apache ECharts? I think you can prevent multiple notifications after reacting to the `rect` onClick if you don't need it.

**Comment by mikhail-vl** [comment]
@treto I have added link to the official documentation in the README.

  Please let me know if there is anything else.
